### ISSUE TITLE
Small mistake in documentation

### ISSUE THREAD

**Issue by DutchMaker** [DoctorWkt/CSCvon8#1]
There seems to be a small mistake in the [Design documentation](https://github.com/DoctorWkt/CSCvon8/blob/master/Docs/CSCvon8_design.md):
In the ALU functions table, the arithmetic and logical shift are reversed.  
It should be logical first and arithmetic second (according to the `gen_alu` script).
Same thing goes for the multiplication low and high bits.

Thanks for this awesome repository. It's been a gold mine for information to me!

**Comment by DoctorWkt** [comment]
No, I think they are right. Look at the `@Opsub` list on lines 135-168 of [gen_alu](https://github.com/DoctorWkt/CSCvon8/blob/master/gen_alu). The arithmetic operations come before the logical operations!
Glad to know you found the project useful.

**Comment by DutchMaker** [comment]
<img width="728" alt="swapped" src="https://user-images.githubusercontent.com/25906944/81301297-29813e80-9079-11ea-8ccc-e62420694df6.png">

Really does seem to be swapped?

**Comment by DoctorWkt** [comment]
Argh yes! Really my bad. Sorry I had misread your original comment as the arithmetic and logical *operations* were reversed. Apologies. You are completely correct and I'll go fix that. Thanks for a) being observant and b) being persistent.

**Comment by DoctorWkt** [comment]
Fixed now.
